<footer>
	<div class="row">
		<div class="left four columns">
			<h3>Contact Us</h3>
			<div>
				<a href="https://twitter.com/muncssociety/">
					<i class="icon-twitter"></i>
					<div class="triangle-right"></div>
					Twitter
				</a>
				<a href="https://www.facebook.com/groups/2202189009/">
					<i class="icon-facebook"></i>
					<div class="triangle-right"></div>
					Facebook
				</a>
				<a href="mailto:muncssociety@gmail.com">
					<i class="icon-envelope"></i>
					<div class="triangle-right"></div>
					Email
				</a>
				<a href="http://muncompsci.ca">
					<i class="icon-globe"></i>
					<div class="triangle-right"></div>
					Website
				</a>
			</div>
		</div>
		<div class="center four columns">
			<h3>Navigation</h3>
			<div>
				<a href="http://community.muncompsci.ca/">Sponsors</a>
				<a href="/privacy">Privacy Policy</a>
				<a>Documentation &amp; Help</a>
				<a href="/terms">Terms of Use</a>
				<a href="http://www.autism.nf.net/">Autism Society of NL</a>
			</div>
		</div>
		<div class="four columns">
			<h3>About Us</h3>
			<div class="about">
				<h4>ABA Lookup</h4>
				<p>
					This software is copyright &copy; MUN Computer Science Society
					and is licensed under the <a>Simplified BSD License</a>.
				</p>
			</div>
		</div>
	</div>
</footer>
