<footer>
	<div class="container clearfix">
		<div class="left">
			<h4>Contact Us</h4>
			<div class="soc">
				<i class="icon-twitter"></i>
			</div>
			<div class="soc-tri"></div>
			<div class="soc-link"><a href="https://twitter.com/muncssociety/">Twitter</a></div>
			<div class="soc">
				<i class="icon-facebook"></i>
			</div>
			<div class="soc-tri"></div>
			<div class="soc-link"><a href="https://www.facebook.com/groups/2202189009/">Facebook</a></div>
			<div class="soc">
				<i class="icon-envelope"></i>
			</div>
			<div class="soc-tri"></div>
			<div class="soc-link"><a href="mailto:muncssociety@gmail.com">Email</a></div>
			<div class="soc">
				<i class="icon-globe"></i>
			</div>
			<div class="soc-tri"></div>
			<div class="soc-link"><a href="http://muncompsci.ca">Website</a></div>
		</div>
		<div class="center">
			<h4>Navigation</h4>
			<a href="http://community.muncompsci.ca/">Sponsors</a>
			<a href="/privacy">Privacy Policy</a>
			<a>Documentation &amp; Help</a>
			<a href="/terms">Terms of Use</a>
			<a href="http://www.autism.nf.net/">Autism Society of NL</a>
		</div>
		<div class="right">
			<h4>About Us</h4>
			<div class="about">
				<h5>ABA Lookup</h5>
				<p>
					This software is copyright &copy; MUN Computer Science Society and is licensed under the GNU GPL.
				</p>
			</div>
		</div>
	</div>
</footer>
