<footer>
	<div class="container">
		<div class="left">
			<h4>Contact Us</h4>
			<div>
				<a href="https://twitter.com/muncssociety/">
					<i class="icon-twitter"></i>
					<div class="triangle-right"></div>
					Twitter
				</a>
				<a href="https://www.facebook.com/groups/2202189009/">
					<i class="icon-facebook"></i>
					<div class="triangle-right"></div>
					Facebook
				</a>
				<a href="mailto:muncssociety@gmail.com">
					<i class="icon-envelope"></i>
					<div class="triangle-right"></div>
					Email
				</a>
				<a href="http://muncompsci.ca">
					<i class="icon-globe"></i>
					<div class="triangle-right"></div>
					Website
				</a>
			</div>
		</div>
		<div class="center">
			<h4>Navigation</h4>
			<div>
				<a href="http://community.muncompsci.ca/">Sponsors</a>
				<a href="/privacy">Privacy Policy</a>
				<a>Documentation &amp; Help</a>
				<a href="/terms">Terms of Use</a>
				<a href="http://www.autism.nf.net/">Autism Society of NL</a>
			</div>
		</div>
		<div class="right">
			<h4>About Us</h4>
			<div class="about">
				<h5>ABA Lookup</h5>
				<p>
					This software is copyright &copy; MUN Computer Science Society
					and is licensed under the modified BSD License.
				</p>
			</div>
		</div>
	</div>
</footer>
