<h2>Your Profile Information</h2>

<p><?php echo $this->error?></p>

<div class="left">
	<h3>Username</h3>
	<label for="username">Username</label>
            <input name="username" value="<?php echo $this->username?>" id="username" type="text" placeholder="Your display name" readonly/>
	<h3>Email Address</h3>
	<label for="email">Email</label>
            <input name="email" value="<?php echo $this->email?>" id="email" type="text" placeholder="Your email" readonly/>
    <h3>Password</h3>

    <h3>Details</h3>
    <p>
        Lorem ipsum dolor sit amet.
    </p>
</div>