<h2>About ABA Lookup</h2>
<p>
	The ABA Lookup tool is designed to facilitate the process of matching ABA therapists with parents of children 
	diagnosed with Autism Spectrum disorder (ASD). This tool supplies parents with the ability to search a database 
	of available therapists, view availability schedules, and initialize contact with therapists. ABA Lookup not 
	only helps parents search for therapists, but also to assist therapists in advertising their practice, allowing
	them to post their weekly availability schedules.
</p>
<p>
	When it comes to finding an Applied Behaviour Analysis (ABA) therapist in guiding the development of your child, 
	parents/guardians often encounter great difficulty acquiring a therapist. That time can be further lengthened by
	the possible incompatibility between the child and therapist or  inconvenient scheduling times with a party. 
	Previously,   this would require parents to start from square one via cumbersome paperwork or  scattered 
	electronic advertisements.  By providing a single website to centralize this process, we aim to drastically 
	decrease the time and effort necessary for typical patient therapist matching. 
<h3>This is another header</h3>
<p>
	Lorem ipsum dolor sit amet, consectetur adipiscing elit.
	Cras ligula turpis, mollis eget ultrices nec, ultricies sit amet purus.
	Aliquam nec nulla orci. Morbi id ornare risus.
	Donec lobortis magna vel nunc posuere porttitor a in ipsum. In tristique fringilla feugiat.
	Phasellus felis neque, posuere sed fringilla sit amet, hendrerit quis augue.
	Donec mauris nunc, vehicula eget sagittis vel, pharetra in elit. Sed lectus elit, congue sit amet tincidunt et, malesuada a dolor.
	Phasellus consectetur eleifend suscipit. Duis nec urna sit amet metus sagittis varius.
	Nunc hendrerit euismod semper. Quisque at massa id quam tristique fringilla.
	Phasellus nec eros libero, ut cursus erat.
</p>
<h3>This is also another header</h3>
<p>
	Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas.
	Vestibulum tortor quam, feugiat vitae, ultricies eget, tempor sit amet, ante.
	Donec eu libero sit amet quam egestas semper. Aenean ultricies mi vitae est.
	Mauris placerat eleifend leo. Quisque sit amet est et sapien ullamcorper pharetra.
	Vestibulum erat wisi, condimentum sed, commodo vitae, ornare sit amet, wisi.
	Aenean fermentum, elit eget tincidunt condimentum, eros ipsum rutrum orci, sagittis tempus lacus enim ac dui.
	Donec non enim in turpis pulvinar facilisis.
	Ut felis. Praesent dapibus, neque id cursus faucibus, tortor neque egestas augue, eu vulputate magna eros eu erat.
	Aliquam erat volutpat. Nam dui mi, tincidunt quis, accumsan porttitor, facilisis luctus, metus
</p>
<p>
	Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas.
	Vestibulum tortor quam, feugiat vitae, ultricies eget, tempor sit amet, ante.
	Donec eu libero sit amet quam egestas semper. Aenean ultricies mi vitae est.
	Mauris placerat eleifend leo. Quisque sit amet est et sapien ullamcorper pharetra.
	Vestibulum erat wisi, condimentum sed, commodo vitae, ornare sit amet, wisi.
	Aenean fermentum, elit eget tincidunt condimentum, eros ipsum rutrum orci, sagittis tempus lacus enim ac dui.
	Donec non enim in turpis pulvinar facilisis.
	Ut felis. Praesent dapibus, neque id cursus faucibus, tortor neque egestas augue, eu vulputate magna eros eu erat.
	Aliquam erat volutpat. Nam dui mi, tincidunt quis, accumsan porttitor, facilisis luctus, metus
</p>
<p>
	Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas.
	Vestibulum tortor quam, feugiat vitae, ultricies eget, tempor sit amet, ante.
	Donec eu libero sit amet quam egestas semper. Aenean ultricies mi vitae est.
	Mauris placerat eleifend leo. Quisque sit amet est et sapien ullamcorper pharetra.
	Vestibulum erat wisi, condimentum sed, commodo vitae, ornare sit amet, wisi.
	Aenean fermentum, elit eget tincidunt condimentum, eros ipsum rutrum orci, sagittis tempus lacus enim ac dui.
	Donec non enim in turpis pulvinar facilisis.
	Ut felis. Praesent dapibus, neque id cursus faucibus, tortor neque egestas augue, eu vulputate magna eros eu erat.
	Aliquam erat volutpat. Nam dui mi, tincidunt quis, accumsan porttitor, facilisis luctus, metus
</p>
