<h2>Change Password</h2>

<p><?php echo $this->error;?></p>

<form action="/user/changepassword" method="post">
    <div class="row">

        <h3>Current Password</h3>
        <label for="password">Enter New Password</label>
        <input name="password" id="password" type="password" placeholder="Current password" required />

        <h3>New Password</h3>
        <label for="password">Enter New Password</label>
        <input name="newpassword" id="newpassword" type="password" placeholder="New password" required />

        <h3>Confirm New Password</h3>
        <label for="password">Enter New Password</label>
        <input name="confirmpassword" id="confirmpassword" type="password" placeholder="Confirm new password" required />


    </div>
    <div class="row">
        <input type="submit" name="submit" id="submit" value="Change" />
    </div>
</form>