<h2>Login to your account</h2>
<?php
	if (isset($this->error)) {
		echo "<p>" . $this->error . "</p>";
	}
?>
<div class="left">
	<form action="/user/login" method="post">
		<div class="row">
			<label for="email-address">Email address</label>
			<input name="email-address" id="email-address" type="email" placeholder="Your email address" required />
		</div>
		<div class="row">
			<label for="password">Password</label>
			<input name="password" id="password" type="password" placeholder="Your password" required />
		</div>
		<div class="row">
			<input name="login" id="login" type="submit" value="Login" />
		</div>
	</form>
</div>
<div class="right">
	<h3>Details</h3>
	<p>Please enter your email and password. Please note that credentials are case-sensitive.</p>
</div>
