<h2>Sign up to start using ABA Lookup</h2>

<p><?php echo $this->error?></p>

<div class="left">
    <form action="/user/register" method="post">
        <div class="row">
            <label for="usertype">User Type</label>
            <select name="usertype" id="usertype">
                <option <?php if ($this->usertype == "parent") {echo "selected";}?> value="parent">Parent</option>
                <option <?php if ($this->usertype == "therapist") {echo "selected";}?> value="therapist">Therapist</option>
            </select>
        </div>
        <div class="row">
            <label for="username">Username</label>
            <input name="username" value="<?php echo $this->username?>" id="username" type="text" placeholder="Your display name" />
        </div>
        <div class="row">
            <label for="emailaddress">Email address</label>
            <input name="emailaddress" value="<?php echo $this->emailaddress?>" id="emailaddress" type="email" placeholder="Email address" />
        </div>
        <div class="row">
            <label for="password">Password</label>
            <input name="password" id="password" type="password" placeholder="Your password" />
        </div>
        <div class="row">
            <label for="confirmpassword">Confirm your password</label>
            <input name="confirmpassword" id="confirmpassword" type="password" placeholder="Confirm your password" />
        </div>
        <div class="row">
            <input name="submit" id="next-step" type="submit" value="Next Step" />
        </div>
    </form>
</div>
<div class="right">
    <h3>Details</h3>
    <p>
        Please specify whether you are a parent seeking treatment for a child or a therapist seeking a client. You will sign in with your username and password. All fields are required.
    </p>
</div>