<h2>Sign up to start using ABA Lookup</h2>
<div class="left">
    <form action="therapistsignup.html" method="post">
        <div class="row">
            <label for="usertype">User Type</label>
            <select id="usertype">
                <option value="parent">Parent</option>
                <option value="therapist">Therapist</option>
            </select>
        </div>
        <div class="row">
            <label for="username">Username</label>
            <input id="username" type="text" placeholder="Your display name" />
        </div>
        <div class="row">
            <label for="emailaddress">Email address</label>
            <input id="emailaddress" type="email" placeholder="Email address" />
        </div>
        <div class="row">
            <label for="password">Password</label>
            <input id="password" type="password" placeholder="Your password" />
        </div>
        <div class="row">
            <label for="confirmpassword">Confirm your password</label>
            <input id="confirmpassword" type="password" placeholder="Confirm your password" />
        </div>
        <div class="row">
            <input id="next-step" type="submit" value="Next Step" />
        </div>
    </form>
</div>
<div class="right">
    <h3>Details</h3>
    <p>
        Lorem ipsum dolor sit amet.
    </p>
</div>