<h2>You have successfully registered.</h2>

<p>
    Thank you for registering with ABA Lookup!
</p>

<p>
    Before you can begin using our service we need to verify your email. We have sent an email to the address
    that you have provided that contains a link. Please click this link to validate your account. This step
    must be completed before you are able to login.
</p>

<p>
    We hope that your experience with ABA Lookup is a good one and that you are able to find
    the therapist that is right for you.  If you would like to get in touch with us to make
    the site better or let us know about your experience, send us a message on facebook or
    tweet at us.  All contact information can be found below.
</p>
