<h2>Forgot Password</h2>
<p><?php echo $this->error; ?></p>

<div class="left">
	<form action="/user/resetpassword" method="post">
		<div class="row">
			<label for="emailaddress">Email address</label>
			<input name="emailaddress" id="emailaddress" type="email" placeholder="Email address" required />
		</div>
		<div class="row">
			<input id="login" type="submit" value="Send" />
		</div>
	</form>
</div>
<div class="right">
	<h3>Forgot Password</h3>
	<p>
		Forgot your password? No problem - just enter the email address associated with your
		account on the left and click the send button.
	</p>
</div>
