<h2>Forgot Password</h2>
<p><?php echo $this->error; ?></p>

<div class="left">
    <form action="/user/resetpassword" method="post">
        <div class="row">
            <label for="emailaddress">Email address</label>
            <input name="emailaddress" id="emailaddress" type="email" placeholder="Email address" required />
        </div>
        <div class="row">
            <input id="login" type="submit" value="Send" />
        </div>
    </form>
</div>
<div class="right">
    <h3>Details</h3>
    <p>
        Forgot your password? Well no problem just enter your e-mail into the space to the left and click the send button below it. We will send out an e-mail containing your user name and password shortly after you click send.
    </p>
</div>