<h2>Reset Password</h2>

<p><?php echo $this->error; ?></p>

<div class="left">
	<form action="/user/updatepassword/<?php echo $this->id; ?>/<?php echo $this->verification; ?>" method="post">
		<div class="row">
			<label for="newpassword">Enter New Password</label>
			<input name="newpassword" id="newpassword" type="password" placeholder="New password" required />
			<label for="confirmpassword">Confirm Password</label>
			<input name="confirmpassword" id="confirmpassword" type="password" placeholder="Confirm password" required />
		</div>
		<div class="row">
			<input name="submit" type="submit" id="submit" value="Change" />
		</div>
	</form>
</div>
<div class="right">
	<h3>Change your password</h3>
	<p>
		Please enter the new password you would like to use and confirm that you have entered it correctly.
	</p>
</div>
