<h2>Howdy, admin!</h2>

<form action="/admin" method="post">
    <input type="text" name="email" id="email">
    <input type="submit" class="button" value="Find By Email">
</form>

<table class="admin_table">
    <thead>
    <tr>
        <th>&nbsp;</th>
        <th>Email</th>
        <th>Display Name</th>
        <th>Tools</th>
    </tr>
    </thead>
    <tbody>


    <?php foreach ($this->model as $m) { ?>
    <tr>
        <td><i class="icon-star"></i></td>
        <td><?php echo $m->getEmail(); ?></td>
        <td><?php echo $m->getDisplayName(); ?></td>
        <td>

            <a href="/admin/delete?user=<?php echo $m->getId(); ?>">Delete</a>
            | <a href="/admin/changepassword?user=<?php echo $m->getId(); ?>">Change Password</a>
            <?php if (!$m->getVerified()) { ?>
                | <a href="/admin/confirm?user=<?php echo $m->getId(); ?>">Confirm Email</a>
            <?php } ?>
            <?php if (!$m->getModerator()) { ?>
                | <a href="/admin/moderator?user=<?php echo $m->getId(); ?>">Make Moderator</a>
            <?php } else { ?>
                | <a href="/admin/unmoderator?user=<?php echo $m->getId(); ?>">Remove Moderator</a>
            <?php } ?>

        </td>
    </tr>
    <?php } ?>

    </tbody>
</table>