<h2>About ABA Lookup</h2>
<p>
	The ABA Lookup tool is designed to facilitate the process of matching Applied Behaviour Analysis (ABA) therapists
	with parents/guardians of children diagnosed with Autism Spectrum Disorder (ASD). It acts as a hub of potential
	ABA therapists for families while making it easier for therapists looking for work to find new clients. The tool
	creates a ranked list of potential therapists for families by matching schedules and locations.
</p>
<h3>Why develop ABA lookup?</h3>
<p>
	The process of finding an ABA therapist to guide the development of your child can be profoundly difficult.
	Parents/guardians often encounter great difficulty acquiring a therapist because of many challenges, including
	possible incompatibility between the child and therapist and conflicting availability between the family and
	the therapist. Before ABA Lookup, finding a new therapist requires families to start from square one every time,
	including chasing cumbersome paperwork or searching through scattered electronic advertisements. By providing a
	single website to centralize this process, we aim to drastically decrease the time and effort necessary for typical patient therapist matching.
</p>
<h2>About us</h3>
<p>
	ABA Lookup was first developed by the Memorial University of Newfoundland (MUN) Computer Science Society in the
	Winter of 2013. The developers were undergraduate students who completed much of the work on a 48-hour Codathon
	from February 17th to February 19th. For more information about the MUN Comp. Sci. society, visit the wiki below!
</p>
