<h2>Finding an ABA therapist has never been easier</h2>
<h3>Matching requirements for both therapists and parents</h3>
<p>
    As a parent/guardian, you can create  a custom schedule to indicate which days/hours of the week you are available 
    for  therapy sessions. The ABA lookup tool will then match you with a therapist according to how well your schedules
    mesh. You can choose to contact a therapist (or as many as you desire), through our service. As an ABA therapist, 
    you can create a schedule denoting your hours of availability as well as your location. Based on the compatibility 
    of your schedules, you will be matched up with patients. You will be notified through email when parents express 
    interest in your services.  After this initial introduction, subsequent communication is to be conducted outside of 
    this website.
</p>
