<?php
	$this->headTitle('ABA Lookup - Connecting families in NL with ABA therapists');
	$this->headMeta()
	     ->appendName('description', '');
?>
<div class="twelve columns">
	<h2>Finding an ABA therapist has never been easier</h2>
	<p>
		ABA Lookup is a hub where families and ABA therapists can connect.
		Parents and ABA therapists can sign-up and indicate their weekly schedule, after which parents can be matched based on schedule compatibility.
	</p>
</div>
