<h2>Privacy Policy</h2>
<div class="left">
	<h3>What information do we collect?</h3>
	<p>
		We collect information from you when you register on our site.
	</p>
	<p>
		Parents: when registering on our site, as appropriate,
		you may be asked to enter your name and e-mail address.
	</p>
	<p>
		ABA Therapists: When registering on our site, as appropriate,
		you may be asked to enter your name, e-mail address,
		qualifications and gender.
	</p>
	<h3>What do we use your information for?</h3>
	<p>
		Any of the information we collect from you may be used in one of the following ways:
	</p>
	<p>
		To improve our website we continually strive to improve our website
		offerings based on the information and feedback we receive from you.
	</p>
	<p>
		Your information, whether public or private, will not be sold,
		exchanged, transferred, or given to any other company for any
		reason whatsoever, without your consent.
	</p>
	<h3>To send periodic emails</h3>
	<p>
		The email address you provide may be used to send you information,
		respond to inquiries, and/or other requests or questions.
	</p>
	<h3>How do we protect your information?</h3>
	<p>
		We implement a variety of security measures to maintain the
		safety of your personal information when you enter,
		submit, or access your personal information.
	</p>
	<h3>Do we use cookies?</h3>
	<p>
		Yes (Cookies are small files that a site or its service provider
		transfers to your computers hard drive through your Web browser
		(if you allow) that enables the sites or service providers systems
		to recognize your browser and capture and remember certain information.
	</p>
	<p>
		We use cookies to understand and save your preferences for future visits.
	</p>
	<h3>Do we disclose any information to outside parties?</h3>
	<p>
		We do not sell, trade, or otherwise transfer to outside parties
		your personally identifiable information. This does not include
		trusted third parties who assist us in operating our website, conducting our business,
		or servicing you, so long as those parties agree to keep this information confidential.
		We may also release your information when we believe release is
		appropriate to comply with the law, enforce our site policies,
		or protect ours or others rights, property, or safety.
	</p>
	<h3>Childrens Online Privacy Protection Act compliance</h3>
	<p>
		We are in compliance with the requirements of COPPA (Childrens Online Privacy Protection Act),
		we do not collect any information from anyone under 13 years of age.
		Our website, products and services are all directed
		to people who are at least 13 years old or older.
	</p>
	<h3>Online privacy policy</h3>
	<p>
		This online privacy policy applies only to information collected
		through our website and not to information collected offline.
	</p>
	<h3>Your consent</h3>
	<p>
		By using our site, you consent to our privacy policy disclosed here.
	</p>
	<h3>Changes to our privacy policy</h3>
	<p>
		If we decide to change our privacy policy, we will post those changes on this page.
	</p>
</div>
