<h2>
                    Web Site Terms and Conditions of Use
                </h2>
			<div class="left">
                <h3>
                    1. Terms
                </h3>
                <p>
                    By accessing this web site, you are agreeing to be bound by these 
                    web site Terms and Conditions of Use, all applicable laws and regulations, 
                    and agree that you are responsible for compliance with any applicable local 
                    laws. If you do not agree with any of these terms, you are prohibited from 
                    using or accessing this site. The materials contained in this web site are 
                    protected by applicable copyright and trade mark law.
</p>

<h3>
	2. Use License
</h3>

<p>
		Permission is hereby granted, free of charge, to any person obtaining a copy of this software and associated documentation files (the "Software"), to deal in the Software without restriction, including without limitation the rights to use, copy, modify, merge, publish, distribute, sublicense, and/or sell copies of the Software, and to permit persons to whom the Software is furnished to do so, subject to the following conditions:

The above copyright notice and this permission notice shall be included in all copies or substantial portions of the Software.
	</p>

<h3>
	3. Disclaimer
</h3>

<p>
		The materials on the ABA Lookup web site are provided "as is". Memorial University Computer Science Society makes no warranties, expressed or implied, and hereby disclaims and negates all other warranties, including without limitation, implied warranties or conditions of merchantability, fitness for a particular purpose, or non-infringement of intellectual property or other violation of rights. Further, Memorial University Computer Science Society does not warrant or make any representations concerning the accuracy, likely results, or reliability of the use of the materials on its Internet web site or otherwise relating to such materials or on any sites linked to this site.
</p>

<h3>
	4. Limitations
</h3>

<p>
	In no event shall Memorial University Computer Science Society or its suppliers be liable for any damages (including, without limitation, damages for loss of data or profit, or due to business interruption,) arising out of the use or inability to use the materials on the ABA Lookup site, even if Memorial University Computer Science Society or a Memorial University Computer Science Society authorized representative has been notified orally or in writing of the possibility of such damage. Because some jurisdictions do not allow limitations on implied warranties, or limitations of liability for consequential or incidental damages, these limitations may not apply to you.
</p>
			
<h3>
	5. Revisions and Errata
</h3>

<p>
	The materials appearing on the ABA Lookup web site could include technical, typographical, or photographic errors. Memorial University Computer Science Society does not warrant that any of the materials on its web site are accurate, complete, or current. Memorial University Computer Science Society may make changes to the materials contained on its web site at any time without notice. Memorial University Computer Science Society does not, however, make any commitment to update the materials.
</p>

<h3>
	6. Links
</h3>

<p>
	Memorial University Computer Science Society has not reviewed all of the sites linked to its Internet web site and is not responsible for the contents of any such linked site. The inclusion of any link does not imply endorsement by Memorial University Computer Science Society of the site. Use of any such linked web site is at the user's own risk.
</p>

<h3>
	7. Site Terms of Use Modifications
</h3>

<p>
	Memorial University Computer Science Society may revise these terms of use for its web site at any time without notice. By using this web site you are agreeing to be bound by the then current version of these Terms and Conditions of Use.
</p>
</div>