<h2>Edit Profile</h2>  <!-- Therapist Profile-->
<p><?php echo $this->error; ?></p>

<div class="left">
    <form action="#" method="#">
        <div class="row">
            <label for="name">Name</label>
            <input name="name" id="name" type="name" placeholder="Name" required />
        </div>
        <div class="row">
            <input id="#" type="#" value="#" />
        </div>
        <div class="row">
            <input id="#" type="#" value="#" />
        </div>
        <div class="row">
            <input id="#" type="#" value="#" />
        </div>
        <div class="row">
            <input id="#" type="#" value="#" />
        </div>
        <div class="row">
            <input id="#" type="#" value="#" />
        </div>
    </form>
</div>
<div class="right">
    <h3>Placeholder label</h3>
    <p>
        
    </p>
</div>