<h2>Your Profile Information</h2>

<p><?php echo $this->error?></p>

<div class="left">
<h3>Username</h3>
	<span name="username" id="username" value="<?php echo $this->username?>" />
	<h3>Email Address</h3>
	<span id="email" name="email" value="<?php echo $this->email?>"/>
	<h3>Sex</h3>
	<span id="sex" name="sex" value="<?php echo $this->sex?>" />
	<h3>Code of Conduct Status</h3>
	<span id="code_of_conduct" name = "code_of_conduct" value="<?php echo $this->code_of_conduct?>" />
	<h3>ABA Course Status</h3>
	<span id="aba_course" name="aba_course" value="<?php echo $this->aba_course?>" />
	<h3>Verification Status</h3>
	<span id="verified" name="verified" value="<?php echo $this->verified?>"/>
<div class="right">
    <h3>Details</h3>
    <p>
        Lorem ipsum dolor sit amet.
    </p>
</div>