<?php
	$this->headTitle('Register - ABA Lookup');
	$this->headMeta()
	     ->appendName('description', '');
?>
<div class="twelve columns">
	<h2>Register to start using ABA Lookup</h2>
	<ul>
		<li><a href="/users/register/parent">I am a parent</a></li>
		<li><a href="/users/register/therapist">I am an ABA therapist</a></li>
	</ul>
	<?php
		if (isset($this->error)) {
			echo "<p>{$this->error}</p>";
		}
		$this->form->setAttribute('class', 'left');
		$this->form->setAttribute('action', sprintf('/users/register/%s', $this->type));
		$this->form->setAttribute('method', 'post');
		echo $this->form()->markup($this->form);
	?>
</div>
