<h2>
	Privacy Policy
</h2>
				<div class="left">

<!-- START PRIVACY POLICY CODE --><div style="font-family: arial;"><span style="font-size: small;">
<h3>What information do we collect?</h3>
</span><br /><br />We collect information from you when you register on our site.</div>
<div style="font-family: arial;"></div>
<div style="font-family: arial;">Parents: <span>When registering on our site, as appropriate, you may be asked to enter your: name and e-mail address.</span> </div>
<div style="font-family: arial;">ABA Therapists: <span>When registering on our site, as appropriate, you may be asked to enter your: name, e-mail address, qualifications and gender. </span><br /><br /><span style="font-size: small;">
<h3>What do we use your information for?</h3>
</span><br /><br />Any of the information we collect from you may be used in one of the following ways: <br /><br />To improve our website<br />We continually strive to improve our website offerings based on the information and feedback we receive from you.<br /><br />To process transactions</div>
<div style="font-family: arial;">
<blockquote>Your information, whether public or private, will not be sold, exchanged, transferred, or given to any other company for any reason whatsoever, without your consent.</blockquote>
<h3>To send periodic emails</h3>
<br /><br />The email address you provide may be used to send you information, respond to inquiries, and/or other requests or questions.<br /><br /><span style="font-size: small;">
<h3>How do we protect your information?</h3>
</span><br /><br />We implement a variety of security measures to maintain the safety of your personal information when you enter, submit, or access your personal information. <br /><br /><span style="font-size: small;">
<h3>Do we use cookies?</h3>
</span><br /><br />Yes (Cookies are small files that a site or its service provider transfers to your computers hard drive through your Web browser (if you allow) that enables the sites or service providers systems to recognize your browser and capture and remember certain information<br /><br /> We use cookies to understand and save your preferences for future visits.<br /><br /><span style="font-size: small;">
<h3>Do we disclose any information to outside parties?</h3>
</span><br /><br />We do not sell, trade, or otherwise transfer to outside parties your personally identifiable information. This does not include trusted third parties who assist us in operating our website, conducting our business, or servicing you, so long as those parties agree to keep this information confidential. We may also release your information when we believe release is appropriate to comply with the law, enforce our site policies, or protect ours or others rights, property, or safety.<br /><br /><span style="font-size: small;">
<h3>Childrens Online Privacy Protection Act Compliance</h3>
</span><br /><br />We are in compliance with the requirements of COPPA (Childrens Online Privacy Protection Act), we do not collect any information from anyone under 13 years of age. Our website, products and services are all directed to people who are at least 13 years old or older.<br /><br /><span style="font-size: small;">
<h3>Online Privacy Policy Only</h3>
</span><br /><br />This online privacy policy applies only to information collected through our website and not to information collected offline.<br /><br /><span style="font-size: small;">
<h3>Your Consent</h3>
</span><br /><br />By using our site, you consent to our <a style="text-decoration: none; color: #3c3c3c;" href="http://www.freeprivacypolicy.com/" target="_blank">websites privacy policy</a>.<br /><br /><span style="font-size: small;">
<h3>Changes to our Privacy Policy</h3>
</span><br /><br />If we decide to change our privacy policy, we will post those changes on this page. <br /><br /><span style="font-size: small;">
<h3>Contacting Us</h3>
</span><br /><br />If there are any questions regarding this privacy policy you may contact us using the information below. <br /><br />www.contactpagehere.com</div>
<div style="font-family: arial;"></div>
<div style="font-family: arial;"></div>
<div style="font-family: arial; text-align: center;">
<h2><em><strong>Thank You</strong></em></h2>
</div><!-- END PRIVACY POLICY CODE -->