<h2>Complete your schedule</h2>
<div class="avail">
	<h3>Add availability:</h3>
	<form action="/schedule/addinterval/<?php echo $this->id; ?>" method="POST">
		<div class="row">
			<label for="day">Day</label>
			<select name="day" id="day">
				<option value="7">Sunday</option>
				<option value="1">Monday</option>
				<option value="2">Tuesday</option>
				<option value="3">Wednesday</option>
				<option value="4">Thursday</option>
				<option value="5">Friday</option>
				<option value="6">Saturday</option>
			</select>
			<label for="start_time">Start time</label>
			<select name="start_time" id="start_time">
				<option value="0:00">12:00 AM</option>
				<option value="0:30">12:30 AM</option>
				<option value="1:00">1:00 AM</option>
				<option value="1:30">1:30 AM</option>
				<option value="2:00">2:00 AM</option>
				<option value="2:30">2:30 AM</option>
				<option value="3:00">3:00 AM</option>
				<option value="3:30">3:30 AM</option>
				<option value="4:00">4:00 AM</option>
				<option value="4:30">4:30 AM</option>
				<option value="5:00">5:00 AM</option>
				<option value="5:30">5:30 AM</option>
				<option value="6:00">6:00 AM</option>
				<option value="6:30">6:30 AM</option>
				<option value="7:00">7:00 AM</option>
				<option value="7:30">7:30 AM</option>
				<option value="800">8:00 AM</option>
				<option value="8:30">8:30 AM</option>
				<option value="9:00">9:00 AM</option>
				<option value="9:30">9:30 AM</option>
				<option value="10:00">10:00 AM</option>
				<option value="10:30">10:30 AM</option>
				<option value="11:00">11:00 AM</option>
				<option value="11:30">11:30 AM</option>
				<option value="12:00">12:00 PM</option>
				<option value="12:30">12:30 PM</option>
				<option value="13:00">1:00 PM</option>
				<option value="13:30">1:30 PM</option>
				<option value="14:00">2:00 PM</option>
				<option value="14:30">2:30 PM</option>
				<option value="15:00">3:00 PM</option>
				<option value="15:30">3:30 PM</option>
				<option value="16:00">4:00 PM</option>
				<option value="16:30">4:30 PM</option>
				<option value="17:00">5:00 PM</option>
				<option value="17:30">5:30 PM</option>
				<option value="18:00">6:00 PM</option>
				<option value="18:30">6:30 PM</option>
				<option value="19:00">7:00 PM</option>
				<option value="19:30">7:30 PM</option>
				<option value="20:00">8:00 PM</option>
				<option value="20:30">8:30 PM</option>
				<option value="21:00">9:00 PM</option>
				<option value="21:30">9:30 PM</option>
				<option value="22:00">10:00 PM</option>
				<option value="22:30">10:30 PM</option>
				<option value="23:00">11:00 PM</option>
				<option value="23:30">11:30 PM</option>
			</select>
			to
			<label for="end_time">Start time</label>
			<select name="end_time" id="end_time">
				<option value="0:00">12:00 AM</option>
				<option value="0:30">12:30 AM</option>
				<option value="1:00">1:00 AM</option>
				<option value="1:30">1:30 AM</option>
				<option value="2:00">2:00 AM</option>
				<option value="2:30">2:30 AM</option>
				<option value="3:00">3:00 AM</option>
				<option value="3:30">3:30 AM</option>
				<option value="4:00">4:00 AM</option>
				<option value="4:30">4:30 AM</option>
				<option value="5:00">5:00 AM</option>
				<option value="5:30">5:30 AM</option>
				<option value="6:00">6:00 AM</option>
				<option value="6:30">6:30 AM</option>
				<option value="7:00">7:00 AM</option>
				<option value="7:30">7:30 AM</option>
				<option value="800">8:00 AM</option>
				<option value="8:30">8:30 AM</option>
				<option value="9:00">9:00 AM</option>
				<option value="9:30">9:30 AM</option>
				<option value="10:00">10:00 AM</option>
				<option value="10:30">10:30 AM</option>
				<option value="11:00">11:00 AM</option>
				<option value="11:30">11:30 AM</option>
				<option value="12:00">12:00 PM</option>
				<option value="12:30">12:30 PM</option>
				<option value="13:00">1:00 PM</option>
				<option value="13:30">1:30 PM</option>
				<option value="14:00">2:00 PM</option>
				<option value="14:30">2:30 PM</option>
				<option value="15:00">3:00 PM</option>
				<option value="15:30">3:30 PM</option>
				<option value="16:00">4:00 PM</option>
				<option value="16:30">4:30 PM</option>
				<option value="17:00">5:00 PM</option>
				<option value="17:30">5:30 PM</option>
				<option value="18:00">6:00 PM</option>
				<option value="18:30">6:30 PM</option>
				<option value="19:00">7:00 PM</option>
				<option value="19:30">7:30 PM</option>
				<option value="20:00">8:00 PM</option>
				<option value="20:30">8:30 PM</option>
				<option value="21:00">9:00 PM</option>
				<option value="21:30">9:30 PM</option>
				<option value="22:00">10:00 PM</option>
				<option value="22:30">10:30 PM</option>
				<option value="23:00">11:00 PM</option>
				<option value="23:30">11:30 PM</option>
			</select>
			<input id="add" type="submit" value="Add" />
		</div>
	</form>
</div>

<table>
<thead>
<tr>
	<th></th>
	<th>Sun</th>
	<th>Mon</th>
	<th>Tue</th>
	<th>Wed</th>
	<th>Thu</th>
	<th>Fri</th>
	<th>Sat</th>
</tr>

</tbody>
</table>

<?php
foreach($this->intervals as $int) {
	echo $int->getWeekDay() . "." . $int->getStartTime() . "." . $int->getEndTime();
}
?>
