<h2>Login to your account</h2>
<?php
	if (isset($this->error)) {
		echo "<p>{$this->error}</p>";
	}
	$this->form->setAttribute('class', 'left');
	$this->form->setAttribute('action', '/users/login');
	$this->form->setAttribute('method', 'post');
	echo $this->form()->openTag($this->form);

	foreach ($this->form as $element) {
?>
	<div class="row">
		<?php
			if ($element->hasAttribute('label')) {
				echo $this->formLabel($element);
			}
			echo $this->formElement($element);
		?>
	</div>
<?php
	}

	echo $this->form()->closeTag();
?>
<div class="right">
	<h3>Details</h3>
	<p>Please enter your email and password. Please note that credentials are case-sensitive.</p>
</div>
