<h2>Your available matches</h2>
<div class="conduct"><i class="icon-legal"></i> Code of Conduct</div>
<div class="match">
	<h5><a href="#">Displayname</a> <i class="icon-legal"></i></h5>
	<div class="email">displayname@web.com</div>
	<div class="other"><b>Score:</b> 99 | <b>Gender:</b> Female</div>
	<ul>
		<li>St. John's East</li>
		<li>St. John's North</li>
		<li>St. John's West</li>
	</ul>
</div>
<div class="match">
	<h5>Displayname <i class="icon-legal"></i></h5>
	<div class="email">displayname@web.com</div>
	<div class="other"><b>Score:</b> 99 | <b>Gender:</b> Female</div>
	<ul>
		<li>St. John's East</li>
		<li>St. John's North</li>
		<li>St. John's West</li>
	</ul>
</div>
<div class="match">
	<h5>Displayname <i class="icon-legal"></i></h5>
	<div class="email">displayname@web.com</div>
	<div class="other"><b>Score:</b> 99 | <b>Gender:</b> Female</div>
	<ul>
		<li>St. John's East</li>
		<li>St. John's North</li>
		<li>St. John's West</li>
	</ul>
</div>
