<?php
	$this->headTitle('Matches - ' . $this->user->getDisplayName());
?>
<div class="twelve columns">
	<h2>Your available matches</h2>
	<div class="conduct"><i class="icon-legal"></i> Has recieved their Certificate of Conduct</div>
	<div class="match">
		<h3>Displayname <i class="icon-legal"></i></h3>
		<div class="email">displayname@web.com</div>
		<div class="other">
			<b>Score:</b> 99 | <b>Gender:</b> Female
		</div>
		<ul>
			<li>St. John's East</li>
			<li>St. John's North</li>
			<li>St. John's West</li>
		</ul>
	</div>
	<div class="match">
		<h3>Displayname <i class="icon-legal"></i></h3>
		<div class="email">displayname@web.com</div>
		<div class="other">
			<b>Score:</b> 99 | <b>Gender:</b> Female
		</div>
		<ul>
			<li>St. John's East</li>
			<li>St. John's North</li>
			<li>St. John's West</li>
		</ul>
	</div>
	<div class="match">
		<h3>Displayname <i class="icon-legal"></i></h3>
		<div class="email">displayname@web.com</div>
		<div class="other">
			<b>Score:</b> 99 | <b>Gender:</b> Female
		</div>
		<ul>
			<li>St. John's East</li>
			<li>St. John's North</li>
			<li>St. John's West</li>
		</ul>
	</div>
</div>
