<?php
	$this->headTitle('Profile - ' . $this->user->getDisplayName());
?>
<div class="eight columns">
	<h2>Edit your profile information</h2>
	<?php
		if (isset($this->error)) {
			echo "<p>{$this->error}</p>";
		}
		$this->form->setAttribute('class', 'left');
		$this->form->setAttribute('action', '/users' . '/' . $this->user->getId() . '/profile/edit');
		$this->form->setAttribute('method', 'post');
		echo $this->form()->markup($this->form);
	?>
</div>
<aside class="aside four columns">
	<h3>Details</h3>
	<p>Edit your profile information.</p>
</aside>
