<?php
	$this->headTitle('Profile - ' . $this->user->getDisplayName());
?>
<div class="eight columns">
	<h2>Your profile information</h2>
	<?php
		if (isset($this->confirm)) {
			echo "<p>{$this->confirm}</p>";
		}
	?>
	<h3>Display name</h3>
	<p><?php echo $this->user->getDisplayName(); ?></p>
	<h3>Email address</h3>
	<p><?php echo $this->user->getEmail(); ?></p>

	<h3>Phone number</h3>
	<p><?php echo $this->user->getPhone() ? $this->user->getPhone() : "n/a"; ?></p>

	<?php if ($this->user->getUserType() === \ABALookup\Entity\UserType::TYPE_ABA_THERAPIST): ?>

	<h3>Gender</h3>
	<p>
		<?php
			$gender = $this->user->getGender();
			if (!isset($gender)) {
				echo "Undisclosed";
			} else {
				echo ($gender == "F") ? "Female" : "Male";
			}
		?>
	</p>
	<h3>Certificate of conduct</h3>
	<p><?php echo $this->user->getCertificateOfConduct(); ?></p>
	<h3>ABA therapy course</h3>
	<p><?php echo ($this->user->getAbaCourse()) ? "Completed" : "Not yet completed"; ?></p>

	<?php endif; ?>

	<a href="<?php echo '/users' . '/' . $this->user->getId() . '/profile/edit' ?>" class="button">Edit your information</a>
</div>
<aside class="aside four columns">
	<h3>Details</h3>
	<p>
		This page contains the information associated with your account
		and may be publically visible.
		The edit button will allow you to edit your information.
	</p>
</aside>
