<h2>Your Profile Information</h2>
<?php
	if ($this->confirm) {
		echo "<p>{$this->confirm}</p>";
	}
?>
<div class="left">
	<h3>Username</h3>
	<p>Your username</p>
	<h3>Email Address</h3>
	<p>Your email@address.com</p>
	<h3>Verification Status</h3>
	<p>Is your email verified boolean?</p>
	<h3>Password</h3>
	<p>Some circles of your password</p>
	<h2>Therapist only</h2>
	<h3>Sex</h3>
	<p>Your gender</p>
	<h3>Code of Conduct Status</h3>
	<p>Status of your Code of Conduct</p>
	<h3>ABA Course Status</h3>
	<p>Status of your ABA Course</p>
	<button id="edit">Edit your profile</button>
</div>
<div class="right">
	<h3>Details</h3>
	<p>
		This page contains the information associated with your account and may be publically visible. The Edit button will allow you to edit your information.
	</p>
</div>
