<div class="eight columns">
	<h2>Your profile information</h2>
	<?php
		if (isset($this->confirm)) {
			echo "<p>{$this->confirm}</p>";
		}
	?>
	<h3>Display name</h3>
	<p><?php echo $this->user->getDisplayName(); ?></p>
	<h3>Email address</h3>
	<p><?php echo $this->user->getEmail(); ?></p>

	<h3>Phone number</h3>
	<p><?php echo $this->user->getPhone() ? $this->user->getPhone() : "n/a"; ?></p>

	<h3>Verification status</h3>
	<p><?php echo ($this->user->getVerified()) ? "Verified" : "You need to verify your email address"; ?></p>

	<?php if ($this->user->getTherapist()): ?>

	<h3>Sex</h3>
	<p>
		<?php
			$sex = $this->user->getSex();
			if (!isset($sex)) {
				echo "Undisclosed";
			} else {
				echo ($sex == "F") ? "Female" : "Male";
			}
		?>
	</p>
	<h3>Code of conduct</h3>
	<p><?php echo ($this->user->getCodeOfConduct()) ? "Accepted" : "You need to accept the code of conduct"; ?></p>
	<h3>ABA therapy course</h3>
	<p><?php echo ($this->user->getAbaCourse()) ? "Completed" : "Not yet completed"; ?></p>

	<?php endif; ?>

	<a href="<?php echo '/users' . '/' . $this->user->getId() . '/profile/edit' ?>" class="button">Edit your information</a>
</div>
<aside class="aside four columns">
	<h3>Details</h3>
	<p>
		This page contains the information associated with your account
		and may be publically visible.
		The edit button will allow you to edit your information.
	</p>
</aside>
