<h2>Register to start using ABA Lookup</h2>
<?php
	foreach ($this->errors as $field => $messages) {
		foreach ($messages as $error => $message) {
			echo "<p><pre>{$field} => {$error} => {$message}</pre></p>";
		}
	}
	$this->form->setAttribute('id', 'register-form');
	$this->form->setAttribute('class', 'left');
	$this->form->setAttribute('action', '/users/register');
	$this->form->setAttribute('method', 'post');
	echo $this->form()->openTag($this->form);

	foreach ($this->form as $element) {
?>
	<div class="row">
		<?php
			if ($element->hasAttribute('label')) {
				echo $this->formLabel($element);
			}
			echo $this->formElement($element);
		?>
	</div>
<?php
	}
	echo $this->form()->closeTag();
?>
<div class="right">
	<h3>Details</h3>
	<p>
		Please specify whether you are a parent seeking
		treatment for a child or a therapist seeking a
		client. You will sign in with your username and password. All fields are required.
	</p>
</div>
