<h2>Register to start using ABA Lookup</h2>
<?php
	if (isset($this->error)) {
		echo "<p>" . $this->error . "</p>";
	}
?>
<form action="/users/register" method="post" class="left">
	<div class="row">
		<label for="user-type">User type</label>
		<select name="user-type" id="user-type">
			<option <?php if ($this->userType == "parent") { echo "selected"; } ?> value="parent">Parent</option>
			<option <?php if ($this->userType == "therapist") { echo "selected"; } ?> value="therapist">Therapist</option>
		</select>
	</div>
	<div class="row">
		<label for="display-name">Display name</label>
		<input name="display-name" value="<?php echo $this->displayName; ?>" id="display-name" type="text" placeholder="Your display name" />
	</div>
	<div class="row">
		<label for="email-address">Email address</label>
		<input name="email-address" value="<?php echo $this->email; ?>" id="email-address" type="email" placeholder="Your email address" />
	</div>
	<div class="row">
		<label for="password">Password</label>
		<input name="password" id="password" type="password" placeholder="Your password" />
	</div>
	<div class="row">
		<label for="confirm-password">Confirm your password</label>
		<input name="confirm-password" id="confirm-password" type="password" placeholder="Confirm your password" />
	</div>
	<div class="row">
		<input type="submit" value="Next Step" />
	</div>
</form>
<div class="right">
	<h3>Details</h3>
	<p>
		Please specify whether you are a parent seeking
		treatment for a child or a therapist seeking a
		client. You will sign in with your username and password. All fields are required.
	</p>
</div>
