<?php
	$this->headTitle('Schedule - ' . $this->user->getDisplayName());
	$helper = $this->scheduleHelper($this->schedule);
?>
<div class="twelve columns">
	<h2>Complete your schedule</h2>
	<?php
		if (isset($this->error)) {
			echo "<p>{$this->error}</p>";
		}
	?>
	<div class="availability">
		<h3>Availability:</h3>
		<form method="post" action="<?php echo "/users/{$this->user->getId()}/schedule/edit"; ?>">
			<div class="row">
				<div class="twelve columns">
				<label for="day">Day</label>
				<select id="day" name="day">
					<?php echo $helper->getSelectOptionsForDays(); ?>
				</select>
				from
				<label for="start-time">Start time</label>
				<select id="start-time" name="start-time">
					<?php echo $helper->getSelectOptionsForTimes(); ?>
				</select>
				to
				<label for="end-time">End time</label>
				<select id="end-time" name="end-time">
					<?php echo $helper->getSelectOptionsForTimes(1); ?>
				</select>
				</div>
			</div>
			<div class="row">
				<div class="twelve columns">
					<input name="add-remove" type="radio" id="add-availability" value="add" checked>
					<label for="add-availability">Add</label>
					<input name="add-remove" type="radio" id="remove-availability" value="remove">
					<label for="remove-availability">Remove</label>
				</div>
			</div>
			<div class="row">
				<div class="twelve columns">
					<input id="update-schedule" type="submit" value="Update schedule">
				</div>
			</div>
		</form>
	</div>
	<div class="row">
		<div class="twelve columns schedule-wrapper">
			<?php echo $helper->renderSchedule(['schedule']); ?>
		</div>
	</div>
</div>
