<h2>Complete your schedule</h2>
<div class="avail">
	<h3>Add availability:</h3>
	<form action="<?php echo $this->profile->url . '/schedule'; ?>">
		<div class="row">
			<label for="day">Day</label>
			<select id="day">
				<option value="sunday">Sunday</option>
				<option value="monday">Monday</option>
				<option value="tuesday">Tuesday</option>
				<option value="wednesday">Wednesday</option>
				<option value="thursday">Thursday</option>
				<option value="friday">Friday</option>
				<option value="saturday">Saturday</option>
			</select>
			<label for="start">Start time</label>
			<select id="start">
				<option value="100am">1:00 AM</option>
				<option value="130am">1:30 AM</option>
				<option value="200am">2:00 AM</option>
				<option value="230am">2:30 AM</option>
				<option value="300am">3:00 AM</option>
				<option value="330am">3:30 AM</option>
				<option value="400am">4:00 AM</option>
				<option value="430am">4:30 AM</option>
				<option value="500am">5:00 AM</option>
				<option value="530am">5:30 AM</option>
				<option value="600am">6:00 AM</option>
				<option value="630am">6:30 AM</option>
				<option value="700am">7:00 AM</option>
				<option value="730am">7:30 AM</option>
				<option value="800am">8:00 AM</option>
				<option value="830am">8:30 AM</option>
				<option value="900am">9:00 AM</option>
				<option value="930am">9:30 AM</option>
				<option value="1000am">10:00 AM</option>
				<option value="1030am">10:30 AM</option>
				<option value="1100am">11:00 AM</option>
				<option value="1130am">11:30 AM</option>
				<option value="1200pm">12:00 PM</option>
				<option value="1230am">12:30 PM</option>
				<option value="100pm">1:00 PM</option>
				<option value="130pm">1:30 PM</option>
				<option value="200pm">2:00 PM</option>
				<option value="230pm">2:30 PM</option>
				<option value="300pm">3:00 PM</option>
				<option value="330pm">3:30 PM</option>
				<option value="400pm">4:00 PM</option>
				<option value="430pm">4:30 PM</option>
				<option value="500pm">5:00 PM</option>
				<option value="530pm">5:30 PM</option>
				<option value="600pm">6:00 PM</option>
				<option value="630pm">6:30 PM</option>
				<option value="700pm">7:00 PM</option>
				<option value="730pm">7:30 PM</option>
				<option value="800pm">8:00 PM</option>
				<option value="830pm">8:30 PM</option>
				<option value="900pm">9:00 PM</option>
				<option value="930pm">9:30 PM</option>
				<option value="1000pm">10:00 PM</option>
				<option value="1030pm">10:30 PM</option>
				<option value="1100pm">11:00 PM</option>
				<option value="1130pm">11:30 PM</option>
				<option value="1200am">12:00 AM</option>
				<option value="1230am">12:30 AM</option>
			</select>
			to
			<label for="end">Start time</label>
			<select id="end">
				<option value="100am">1:00 AM</option>
				<option value="130am">1:30 AM</option>
				<option value="200am">2:00 AM</option>
				<option value="230am">2:30 AM</option>
				<option value="300am">3:00 AM</option>
				<option value="330am">3:30 AM</option>
				<option value="400am">4:00 AM</option>
				<option value="430am">4:30 AM</option>
				<option value="500am">5:00 AM</option>
				<option value="530am">5:30 AM</option>
				<option value="600am">6:00 AM</option>
				<option value="630am">6:30 AM</option>
				<option value="700am">7:00 AM</option>
				<option value="730am">7:30 AM</option>
				<option value="800am">8:00 AM</option>
				<option value="830am">8:30 AM</option>
				<option value="900am">9:00 AM</option>
				<option value="930am">9:30 AM</option>
				<option value="1000am">10:00 AM</option>
				<option value="1030am">10:30 AM</option>
				<option value="1100am">11:00 AM</option>
				<option value="1130am">11:30 AM</option>
				<option value="1200pm">12:00 PM</option>
				<option value="1230am">12:30 PM</option>
				<option value="100pm">1:00 PM</option>
				<option value="130pm">1:30 PM</option>
				<option value="200pm">2:00 PM</option>
				<option value="230pm">2:30 PM</option>
				<option value="300pm">3:00 PM</option>
				<option value="330pm">3:30 PM</option>
				<option value="400pm">4:00 PM</option>
				<option value="430pm">4:30 PM</option>
				<option value="500pm">5:00 PM</option>
				<option value="530pm">5:30 PM</option>
				<option value="600pm">6:00 PM</option>
				<option value="630pm">6:30 PM</option>
				<option value="700pm">7:00 PM</option>
				<option value="730pm">7:30 PM</option>
				<option value="800pm">8:00 PM</option>
				<option value="830pm">8:30 PM</option>
				<option value="900pm">9:00 PM</option>
				<option value="930pm">9:30 PM</option>
				<option value="1000pm">10:00 PM</option>
				<option value="1030pm">10:30 PM</option>
				<option value="1100pm">11:00 PM</option>
				<option value="1130pm">11:30 PM</option>
				<option value="1200am">12:00 AM</option>
				<option value="1230am">12:30 AM</option>
			</select>
			<input id="add" type="submit" value="Add" />
		</div>
	</form>
</div>
<form action="<?php echo $profile->url . '/schedule'; ?>" method="post">
	<table>
		<thead>
			<tr>
				<th></th>
				<th>Sun</th>
				<th>Mon</th>
				<th>Tue</th>
				<th>Wed</th>
				<th>Thu</th>
				<th>Fri</th>
				<th>Sat</th>
			</tr>
			<tr>
				<th></th>
				<th></th>
				<th></th>
				<th></th>
				<th></th>
				<th></th>
				<th></th>
				<th></th>
			</tr>
		</thead>
		<tbody>
			<tr>
				<td>1 AM</td>
				<td>
					<input id="1AM-sunday" type="checkbox" />
				</td>
				<td>
					<input id="1AM-monday" type="checkbox" />
				</td>
				<td>
					<input id="1AM-tuesday" type="checkbox" />
				</td>
				<td>
					<input id="1AM-wednesday" type="checkbox" />
				</td>
				<td>
					<input id="1AM-thursday" type="checkbox" />
				</td>
				<td>
					<input id="1AM-friday" type="checkbox" />
				</td>
				<td>
					<input id="1AM-saturday" type="checkbox" />
				</td>
			</tr>
			<tr>
				<td>&nbsp;</td>
				<td></td>
				<td></td>
				<td></td>
				<td></td>
				<td></td>
				<td></td>
				<td></td>
			</tr>
			<tr>
				<td>2 AM</td>
				<td></td>
				<td class="selected start">
					Available
					<div class="close"><a href="#">x</a></div>
				</td>
				<td></td>
				<td></td>
				<td></td>
				<td></td>
				<td></td>
			</tr>
			<tr>
				<td>&nbsp;</td>
				<td></td>
				<td class="selected"></td>
				<td></td>
				<td></td>
				<td></td>
				<td></td>
				<td></td>
			</tr>
			<tr>
				<td>3 AM</td>
				<td></td>
				<td></td>
				<td></td>
				<td></td>
				<td></td>
				<td></td>
				<td></td>
			</tr>
			<tr>
				<td>&nbsp;</td>
				<td></td>
				<td></td>
				<td></td>
				<td></td>
				<td></td>
				<td></td>
				<td></td>
			</tr>
			<tr>
				<td>4 AM</td>
				<td></td>
				<td></td>
				<td></td>
				<td></td>
				<td></td>
				<td></td>
				<td></td>
			</tr>
			<tr>
				<td>&nbsp;</td>
				<td></td>
				<td></td>
				<td></td>
				<td></td>
				<td></td>
				<td></td>
				<td></td>
			</tr>
			<tr>
				<td>5 AM</td>
				<td></td>
				<td></td>
				<td></td>
				<td></td>
				<td></td>
				<td></td>
				<td></td>
			</tr>
			<tr>
				<td>&nbsp;</td>
				<td></td>
				<td></td>
				<td></td>
				<td></td>
				<td></td>
				<td></td>
				<td></td>
			</tr>
			<tr>
				<td>6 AM</td>
				<td></td>
				<td></td>
				<td></td>
				<td></td>
				<td></td>
				<td></td>
				<td></td>
			</tr>
			<tr>
				<td>&nbsp;</td>
				<td></td>
				<td></td>
				<td></td>
				<td></td>
				<td></td>
				<td></td>
				<td></td>
			</tr>
			<tr>
				<td>7 AM</td>
				<td></td>
				<td></td>
				<td></td>
				<td></td>
				<td></td>
				<td></td>
				<td></td>
			</tr>
			<tr>
				<td>&nbsp;</td>
				<td></td>
				<td></td>
				<td></td>
				<td></td>
				<td></td>
				<td></td>
				<td></td>
			</tr>
			<tr>
				<td>8 AM</td>
				<td></td>
				<td></td>
				<td></td>
				<td></td>
				<td></td>
				<td></td>
				<td></td>
			</tr>
			<tr>
				<td>&nbsp;</td>
				<td></td>
				<td></td>
				<td></td>
				<td></td>
				<td></td>
				<td></td>
				<td></td>
			</tr>
			<tr>
				<td>9 AM</td>
				<td></td>
				<td></td>
				<td></td>
				<td></td>
				<td></td>
				<td></td>
				<td></td>
			</tr>
			<tr>
				<td>&nbsp;</td>
				<td></td>
				<td></td>
				<td></td>
				<td></td>
				<td></td>
				<td></td>
				<td></td>
			</tr>
			<tr>
				<td>10 AM</td>
				<td></td>
				<td></td>
				<td></td>
				<td></td>
				<td></td>
				<td></td>
				<td></td>
			</tr>
			<tr>
				<td>&nbsp;</td>
				<td></td>
				<td></td>
				<td></td>
				<td></td>
				<td></td>
				<td></td>
				<td></td>
			</tr>
			<tr>
				<td>11 AM</td>
				<td></td>
				<td></td>
				<td></td>
				<td></td>
				<td></td>
				<td></td>
				<td></td>
			</tr>
			<tr>
				<td>&nbsp;</td>
				<td></td>
				<td></td>
				<td></td>
				<td></td>
				<td></td>
				<td></td>
				<td></td>
			</tr>
			<tr>
				<td>12 PM</td>
				<td></td>
				<td></td>
				<td></td>
				<td></td>
				<td></td>
				<td></td>
				<td></td>
			</tr>
			<tr>
				<td>&nbsp;</td>
				<td></td>
				<td></td>
				<td></td>
				<td></td>
				<td></td>
				<td></td>
				<td></td>
			</tr>
			<tr>
				<td>1 PM</td>
				<td></td>
				<td></td>
				<td></td>
				<td></td>
				<td></td>
				<td></td>
				<td></td>
			</tr>
			<tr>
				<td>&nbsp;</td>
				<td></td>
				<td></td>
				<td></td>
				<td></td>
				<td></td>
				<td></td>
				<td></td>
			</tr>
			<tr>
				<td>2 PM</td>
				<td></td>
				<td></td>
				<td></td>
				<td></td>
				<td></td>
				<td></td>
				<td></td>
			</tr>
			<tr>
				<td>&nbsp;</td>
				<td></td>
				<td></td>
				<td></td>
				<td></td>
				<td></td>
				<td></td>
				<td></td>
			</tr>
			<tr>
				<td>3 PM</td>
				<td></td>
				<td></td>
				<td></td>
				<td></td>
				<td></td>
				<td></td>
				<td></td>
			</tr>
			<tr>
				<td>&nbsp;</td>
				<td></td>
				<td></td>
				<td></td>
				<td></td>
				<td></td>
				<td></td>
				<td></td>
			</tr>
			<tr>
				<td>4 PM</td>
				<td></td>
				<td></td>
				<td></td>
				<td></td>
				<td></td>
				<td></td>
				<td></td>
			</tr>
			<tr>
				<td>&nbsp;</td>
				<td></td>
				<td></td>
				<td></td>
				<td></td>
				<td></td>
				<td></td>
				<td></td>
			</tr>
			<tr>
				<td>5 PM</td>
				<td></td>
				<td></td>
				<td></td>
				<td></td>
				<td></td>
				<td></td>
				<td></td>
			</tr>
			<tr>
				<td>&nbsp;</td>
				<td></td>
				<td></td>
				<td></td>
				<td></td>
				<td></td>
				<td></td>
				<td></td>
			</tr>
			<tr>
				<td>6 PM</td>
				<td></td>
				<td></td>
				<td></td>
				<td></td>
				<td></td>
				<td></td>
				<td></td>
			</tr>
			<tr>
				<td>&nbsp;</td>
				<td></td>
				<td></td>
				<td></td>
				<td></td>
				<td></td>
				<td></td>
				<td></td>
			</tr>
			<tr>
				<td>7 PM</td>
				<td></td>
				<td></td>
				<td></td>
				<td></td>
				<td></td>
				<td></td>
				<td></td>
			</tr>
			<tr>
				<td>&nbsp;</td>
				<td></td>
				<td></td>
				<td></td>
				<td></td>
				<td></td>
				<td></td>
				<td></td>
			</tr>
			<tr>
				<td>8 PM</td>
				<td></td>
				<td></td>
				<td></td>
				<td></td>
				<td></td>
				<td></td>
				<td></td>
			</tr>
			<tr>
				<td>&nbsp;</td>
				<td></td>
				<td></td>
				<td></td>
				<td></td>
				<td></td>
				<td></td>
				<td></td>
			</tr>
			<tr>
				<td>9 PM</td>
				<td></td>
				<td></td>
				<td></td>
				<td></td>
				<td></td>
				<td></td>
				<td></td>
			</tr>
			<tr>
				<td>&nbsp;</td>
				<td></td>
				<td></td>
				<td></td>
				<td></td>
				<td></td>
				<td></td>
				<td></td>
			</tr>
			<tr>
				<td>10 PM</td>
				<td></td>
				<td></td>
				<td></td>
				<td></td>
				<td></td>
				<td></td>
				<td></td>
			</tr>
			<tr>
				<td>&nbsp;</td>
				<td></td>
				<td></td>
				<td></td>
				<td></td>
				<td></td>
				<td></td>
				<td></td>
			</tr>
			<tr>
				<td>11 PM</td>
				<td></td>
				<td></td>
				<td></td>
				<td></td>
				<td></td>
				<td></td>
				<td></td>
			</tr>
			<tr>
				<td>&nbsp;</td>
				<td></td>
				<td></td>
				<td></td>
				<td></td>
				<td></td>
				<td></td>
				<td></td>
			</tr>
			<tr>
				<td>12 PM</td>
				<td></td>
				<td></td>
				<td></td>
				<td></td>
				<td></td>
				<td></td>
				<td></td>
			</tr>
			<tr>
				<td>&nbsp;</td>
				<td></td>
				<td></td>
				<td></td>
				<td></td>
				<td></td>
				<td></td>
				<td></td>
			</tr>
		</tbody>
	</table>
</form>
