#!/usr/bin/env php
<?php

error_reporting(E_ALL | E_STRICT);

if (count($argv) !== 3) {
	printf("Data Source Name and SQL file must be passed as arguments.\n");
	die(1);
}

$dsn     = $argv[1];
$sqlfile = $argv[2];
try {
	$sql = new PDO($dsn);
	$sql->setAttribute(PDO::ATTR_ERRMODE, PDO::ERRMODE_EXCEPTION);
	$sql->exec(file_get_contents($sqlfile));
} catch(PDOException $e) {
	printf("Bad things happened.\n");
}
