#!/usr/bin/env python

import sqlite3
sql = sqlite3.connect("database/db.sqlite3")
sql.execute("""INSERT INTO users VALUES(
	1, 'Jan', 'jan@foo.com',
	'$2y$05$1lO333clAqvsZSjjDynC1OLyqgB9JZte422rydkpJp/EE/hin9RYq',
	7095551234, 'therapist', 'M', NULL, NULL, NULL
);""")
sql.commit()
