<?php echo $this->doctype() . "\n"; ?>
<html lang="en">
<head>
	<meta charset="utf-8" />
	<meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1" />
	<?php echo $this->headTitle('ABA Lookup - Connecting Families with ABA Therapists'); ?>
	<meta name="description" content="" />
	<?php
		echo $this->headLink()->prependStylesheet($this->basePath() . "/css/font-awesome.css")
							  ->prependStylesheet($this->basePath() . "/css/general.css")
							  ->prependStylesheet($this->basePath() . "/css/index.css");
	?>
</head>
<body>
<header>
	<div class="container clearfix">
		<a href="/">
			<h1>ABA Lookup</h1>
		</a>
		<nav class="right">
			<?php
				if (isset($this->profile)):
					echo '<a href="' . $this->profile->url . '" class="button">' . $this->profile->getDisplayName() . '</a>';
					echo '<a href="/users/logout">Logout</a>';
				else:
			?>
			<a href="/users/login" class="button">Login</a>
			<a href="/users/register">Signup</a>
			<?php
				endif;
			?>
		</nav>
	</div>
</header>
<div id="intro">
	<span class="yella">Connecting</span> families in<br>Newfoundland &amp; Labrador<br>with ABA therapists<br>
	<div class="learn">
		<a class="button" href="/about">Learn More</a>
	</div>
</div>
<div id="content">
	<div class="container">
		<?php echo $this->content; ?>
	</div>
</div>
<?php echo $this->footer; ?>
<script>
	WebFontConfig = {
		google: { families: [ 'Open+Sans:400,800,700:latin' ] }
	};
	(function() {
		var wf = document.createElement('script');
		wf.src = 'https://ajax.googleapis.com/ajax/libs/webfont/1/webfont.js';
		wf.type = 'text/javascript';
		wf.async = 'true';
		var s = document.getElementsByTagName('script')[0];
		s.parentNode.insertBefore(wf, s);
	})();
</script>
</body>
</html>
