<?php echo $this->doctype(); ?>
<html lang="en">
	<head>
		<meta charset="utf-8">
		<?php echo $this->headTitle('ABA Lookup - Connecting Families with ABA Therapists'); ?>
		<meta name="description" content="">
		<?php echo $this->headLink()->appendStylesheet($this->basePath() . '/css/home.css'); ?>
	</head>
	<body>
		<header>
			<div class="container">
				<a href="/"><h1 class="logo">ABA Lookup</h1></a>
				<nav class="right">
					<?php if (isset($this->user)): ?>
					<a href="<?php echo $this->user->getUrlBase() . 'profile'; ?>" class="button"><?php echo $this->user->getDisplayName(); ?></a>
					<a href="/users/logout">Logout</a>
					<?php else: ?>
					<a href="/users/login" class="button">Login</a>
					<a href="/users/register">Signup</a>
					<?php endif; ?>
				</nav>
			</div>
		</header>
		<div class="intro">
			<span class="yellow">Connecting</span> families in<br>Newfoundland &amp; Labrador<br>with ABA therapists<br>
			<div class="learn">
				<a href="/about" class="button">Learn More</a>
			</div>
		</div>
		<div class="main">
			<div class="container">
				<?php echo $this->content; ?>
			</div>
		</div>
		<?php echo $this->footer; ?>
	</body>
</html>
