<?php echo $this->doctype() . "\n"; ?>
<html lang="en">
<head>
	<meta charset="utf-8" />
	<meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1" />
	<?php echo $this->headTitle("ABA Lookup")->setSeparator(':'); ?>
	<meta name="description" content="" />

	<?php echo $this->headLink()->prependStylesheet($this->basePath() . "/css/font-awesome.css")
								->prependStylesheet($this->basePath() . "/css/general.css")
								->prependStylesheet($this->basePath() . "/css/style.css")
								->prependStylesheet($this->basePath() . "/css/admin.css")
								->prependStylesheet($this->basePath() . "/css/schedule.css");
	?>

</head>
<body>
<header>
	<div class="container clearfix">
		<a href="/">
			<h1>ABA Lookup</h1>
		</a>

		<nav class="right">
			<a href="<?php echo $this->user->getUrlBase() . 'profile'; ?>">Profile</a>
			<a href="<?php echo $this->user->getUrlBase() . 'schedule'; ?>">Schedule</a>
			<a href="<?php echo $this->user->getUrlBase() . 'matches'; ?>">Matches</a>
			<a href="/users/logout">Logout</a>
		</nav>

	</div>
</header>
<div id="content">
	<div class="container clearfix">
		<?php echo $this->content; ?>
	</div>
</div>
<?php echo $this->footer; ?>
<script type="text/javascript">
	WebFontConfig = {
		google: { families: [ 'Open+Sans:400,800,700:latin' ] }
	};
	(function() {
		var wf = document.createElement('script');
		wf.src = 'https://ajax.googleapis.com/ajax/libs/webfont/1/webfont.js';
		wf.type = 'text/javascript';
		wf.async = 'true';
		var s = document.getElementsByTagName('script')[0];
		s.parentNode.insertBefore(wf, s);
	})();
</script>
</body>
</html>
