<?php echo $this->doctype(); ?>
<!-- paulirish.com/2008/conditional-stylesheets-vs-css-hacks-answer-neither/ -->
<!--[if IE 8]><html class="no-js lt-ie9" lang="en"><![endif]-->
<!--[if gt IE 8]><!--><html class="no-js" lang="en"><!--<![endif]-->
	<head>
		<meta charset="utf-8">
		<?php
			echo $this->headTitle();
			echo $this->headMeta()
			          ->appendName('viewport', 'width=device-width');
			echo $this->headLink()
			          ->appendStylesheet($this->basePath('css/app.layout.css'));
		?>
	</head>
	<body>
		<header>
			<div class="row">
				<a href="/" class="four columns mobile-ten">
					<h1 class="logo">ABA Lookup</h1>
				</a>
				<?php if (isset($this->user)): ?>
				<nav class="nav eight columns mobile-ten">
					<a href="<?php echo '/users' . '/' . $this->user->getId() . '/profile'; ?>">Profile</a>
					<a href="<?php echo '/users' . '/' . $this->user->getId() . '/schedule'; ?>">Schedule</a>
					<a href="<?php echo '/users' . '/' . $this->user->getId() . '/matches'; ?>">Matches</a>
					<a href="/users/logout">Logout</a>
				</nav>
				<?php endif; ?>
			</div>
		</header>
		<div class="main">
			<div class="row">
				<?php echo $this->content; ?>
			</div>
		</div>
		<?php echo $this->footer; ?>
	</body>
</html>
