<?php
    echo $this->doctype();
?>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1" />
    <?php echo $this->headTitle("ABA Lookup")->setSeparator(':'); ?>
    <meta name="description" content="" />

    <?php echo $this->headLink()->prependStylesheet($this->basePath() . "/css/font-awesome.css")
                                ->prependStylesheet($this->basePath() . "/css/general.css")
                                ->prependStylesheet($this->basePath() . "/css/style.css");
    ?>

</head>
<body>
<header>
    <div class="container clearfix">
        <h1>ABA Lookup</h1>
        <!--
        <nav class="right">
            <div class="icon">
                <i class="icon-search"></i>
            </div>
            <a href="#">Search</a>
            <div class="icon">
                <i class="icon-user"></i>
            </div>
            <a href="#">My Profile</a>
        </nav>
        -->
    </div>
</header>
<div id="content">
    <div class="container clearfix">
        <?php echo $this->content; ?>
    </div>
</div>
<footer>
    <div class="container clearfix">
        <div class="left">
            <h4>Contact Us</h4>
            <div class="soc">
                <i class="icon-twitter"></i>
            </div>
            <div class="soc-tri"></div>
            <div class="soc-link">Twitter</div>
            <div class="soc">
                <i class="icon-facebook"></i>
            </div>
            <div class="soc-tri"></div>
            <div class="soc-link">Facebook</div>
            <div class="soc">
                <i class="icon-envelope"></i>
            </div>
            <div class="soc-tri"></div>
            <div class="soc-link">Email</div>
            <div class="soc">
                <i class="icon-globe"></i>
            </div>
            <div class="soc-tri"></div>
            <div class="soc-link">Website</div>
            <!--
                Ideally I'd like this
                <a class="social" href="#">
                    <i class="icon-twitter"></i>
                    Twitter
                </a>
                But I'd at least be happy with this
                <a class="social" href="#">
                    <i class="icon-facebook"></i>
                    <span class="social-triangle"></span>
                    Facebook
                </a>
            -->
        </div>
        <div class="center">
            <h4>Navigation</h4>
            <a href="#">Sponsors</a>
            <a href="#">Documentation &amp; Help</a>
            <a href="#">MUN CompSci Society</a>
            <a href="#">Autism Society NL</a>
            <a href="#">Other Resources</a>
        </div>
        <div class="right">
            <h4>About Us</h4>
            <div class="about">
                <h5>ABA Lookup</h5>
                <p>
                    This software is copyright MUN Comp Sci Community Initiative and is licensed under MIT Open Source restrictions.
                </p>
            </div>
        </div>
    </div>
</footer>
<script type="text/javascript">
    WebFontConfig = {
        google: { families: [ 'Open+Sans:400,800,700:latin' ] }
    };
    (function() {
        var wf = document.createElement('script');
        wf.src = 'https://ajax.googleapis.com/ajax/libs/webfont/1/webfont.js';
        wf.type = 'text/javascript';
        wf.async = 'true';
        var s = document.getElementsByTagName('script')[0];
        s.parentNode.insertBefore(wf, s);
    })();
</script>
</body>
</html>
